VINASIC/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using VINASIC.Business.Interface;
using VINASIC.Business.Interface.Enum;
using VINASIC.Business.Interface.Model;
using VINASIC.Models;

namespace VINASIC.Controllers
{
    public class SharedController : BaseController
    {

        private readonly IBLLMenuCategory _bllCategory;
        private readonly IBllNotification _bllNotification;
        public SharedController(IBLLMenuCategory bllCategory, IBllNotification bllNotification)
        {
            _bllCategory = bllCategory;
            _bllNotification = bllNotification;
        }
        public ActionResult HeadMasterPartial()
        {
            ViewBag.ClientName = UserContext.EmployeeName;
            ViewBag.ClientId = UserContext.UserID;
            var userNotification = GetListNotification();
            ViewData["UserNotification"] = userNotification;
            return PartialView(UserContext);
        }
        public List<string> GetListNotification()
        {
            var jss = new JavaScriptSerializer();
            var returnValues = _bllNotification.GetListNotification();
            return (from returnValue in returnValues let lstUser = returnValue.ListUser.Split(',') where lstUser.Contains(UserContext.UserID.ToString()) select returnValue.Description).ToList();
        }

        [HttpPost]
        public JsonResult UpdateNotification()
        {
            try
            {
                _bllNotification.UpdateNotification(UserContext.UserID.ToString());
                return Json(new { Result = "OK", Records = "True" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        public ActionResult MenuLeftMasterPartial()
        {
            List<ModelMenuCategory> listMenuCategory = null;
            try
            {
                listMenuCategory = _bllCategory.GetMenusAndMenuCategoriesByUserId(1, eMenuCategoryType.Left);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return PartialView(listMenuCategory);
        }

        public ActionResult MenuTopMasterPartial()
        {
            return PartialView();
        }

    }
}

VINASIC/Views/Shared/MenuLeftMasterPartial.cshtml
@model List<ModelMenuCategory>
@using VINASIC.Business.Interface.Model;
@{
    List<ModelMenuCategory> listMenuCategory = Model;
}
<!--sidebar start-->
<aside>
    @if (listMenuCategory != null)
{
    <div id="sidebar" class="nav-collapse ">
        <ul class="sidebar-menu">
            <li class="active">
                <a class="" href="/ContentPage/IndexView?code=1">
                    <i class="icon_house_alt"></i>
                    <span>Trang Chủ</span>
                </a>
            </li>
            @for (int i = 0; i < listMenuCategory.Count; i++)
            {
                <li class="sub-menu">
                    <a href="javascript:void(0)" class="">
                        <i class="@listMenuCategory[i].Icon"></i>
                        <span>@listMenuCategory[i].Category</span>
                      
                    </a>
                    @if (listMenuCategory[i].listMenu != null)
                    {
                        var menus = listMenuCategory[i].listMenu;
                        HtmlString img = null;
                        if (menus.Count > 0)
                        {
                        <ul class="sub">
                            @foreach (var menu in menus)
                            {
                                <li><a class="" href="@menu.Link">@menu.MenuName</a></li>
                            }
                        </ul>
                        }
                    }
                </li>
            }
        </ul>
    </div>
}
</aside>
<!--sidebar end-->

VINASIC/Views/Shared/MenuTopMasterPartial.cshtml
@*@model List<SystemAccount.Bussiness.Interface.Model.ModelMenuCategory>
@using SystemAccount.Bussiness.Interface.Model;
@{
    string checkCategoryName = string.Empty ;
    string[] arrClass = { "", "sub-nav-1", "sub-nav-2", "sub-nav-3" };
    string[] width = { "", "suv-nav-width-1", "suv-nav-width-2", "suv-nav-width-3" };
    float sodong = 5;
    float column = 0;
    List<ModelMenuCategory> listMenuCategory = Model;    
  }*@

<div class="navbar " style="margin:0">
    <div class="navbar-inner custom-inner" style="min-height:35px ; height:35px">
        <div class="container">
            <div id="button-menu-left" btn="close-left"   title="Ẩn Menu Trái." data-toggle="tooltip" data-placement="bottom"></div>
                        
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".RightMenu">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>  
                        
            <div class="nav-collapse collapse RightMenu">
                @*<ul class="nav navbar-nav navigation">*@
                  @*  @if (Model != null)
                    {
                        for (int ngang = 0; ngang < listMenuCategory.Count; ngang++)
                        {                             
                            <li>
                                <a href="@listMenuCategory[ngang].Link">@listMenuCategory[ngang].Category</a>
                               @{ 
                                    var menus = listMenuCategory[ngang].listMenu;
                                    if (menus!=null &&  menus.Count > 0)
                                    {
                                        int kt = (menus.Count / (int)sodong);
                                        column = ((float)menus.Count / sodong);
                                        column = (menus.Count > sodong ? ((float)kt == column ? kt : (kt + 1)) : 1);
                                        int index = column > 3 ? 3 : (int)column;
                                        if (menus.Count <= sodong)
                                        {
                                            <ul class="sub-nav @( ngang > 3 ? @arrClass[index]:"") @width[index]">
                                                <li>
                                                    <ul>
                                                        @for (int doc = 0; doc < menus.Count; doc++)
                                                        {
                                                            <li style="float:none"><a href="@menus[doc].Link">@menus[doc].MenuName</a></li>
                                                        }
                                                    </ul>
                                                </li>                              
                                            </ul>
                                        }
                                        else{
                                            <ul class="sub-nav @( ngang > 2 ? @arrClass[index]:"") @width[index]">
                                                @for (int ngangS = 0; ngangS < column; ngangS++)
                                                {                                                    
                                                    <li style="@(ngangS == 2?"border-right:none":"")">
                                                        <ul>
                                                            @for (int doc = 0; doc < menus.Count; doc++)
                                                            {
                                                                int vt =((ngangS * (int)sodong) + doc);
                                                                if (menus.Count > vt && doc < (int)sodong)
                                                                {
                                                                    <li style="float:none"><a href="@menus[vt].Link">@menus[vt].MenuName</a></li>
                                                                }
                                                                else{
                                                                    break;
                                                                }                                                                
                                                            }
                                                        </ul>
                                                    </li>
                                                }                                                                              
                                            </ul>
                                        } 
                                    }  
                                }  *@
       @*                    </li>
                        }                     
                    }                            
              </ul>*@
            </div>  
        </div>
    </div>
</div>

VINASIC/Views/Shared/_ErrorLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/VINASIC/ErrorPage/Error.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-1.10.2.js"></script>
    @*boostrap references*@
    <link href="~/Content/Bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Bootstrap/css/bootstrap-responsive.css" rel="stylesheet" />
    <link href="~/Content/Bootstrap/css/customizebootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/Boostrap/bootstrap.js"></script>


</head>
<body>
   
        @RenderBody()
   
</body>
</html>

VINASIC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="manifest" href="https://phanmem.thegioiinan.today/manifest.json">
    <meta name="_token" content="ZNE4I7MD5VY1Yw2akKB7pSNBwNAlEfQCwhfFNO16">
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/modernizr-2.5.3.js"></script>
    @*boostrap references*@
    <link href="~/Content/Bootstrap/css/bootstrap-responsive.css" rel="stylesheet" />
    @*Jquery Ui references*@
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/Jquery-UI/customizeJqueryUI.css" rel="stylesheet" />
    @*Jtable JS*@
    <link href="~/Content/Jtable/themes/metro/blue/jtable.css" rel="stylesheet" />
    <link href="~/Content/Jtable/customizejtable.css" rel="stylesheet" />
    @*Common*@
    <link href="~/Content/Jquery.alerts/jquery.alerts.css" rel="stylesheet" />
    @*New Layout CSS*@
    <!-- Latest compiled and minified CSS -->
    <link href="~/Content/bootstrap3.3.7.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme3.3.7.min.css" rel="stylesheet" />


    <!-- Latest compiled and minified JavaScript -->
    <script src="~/js/bootstrap3.3.7.min.js"></script>
    @*<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>*@
    <!-- Bootstrap CSS -->
    @*<link href="~/css/bootstrap.min.css" rel="stylesheet">*@
    <!-- bootstrap theme -->
    @* <link href="~/css/bootstrap-theme.css" rel="stylesheet">*@
    <!--external css-->
    <!-- font icon -->
    <link href="~/css/elegant-icons-style.css" rel="stylesheet" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <!-- full calendar css-->
    <link href="~/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css" rel="stylesheet" />
    <link href="~/assets/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" />
    <!-- easy pie chart-->
    <link href="~/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />
    <!-- owl carousel -->
    @*<link rel="stylesheet" href="~/css/owl.carousel.css" type="text/css">*@
    <link href="~/css/jquery-jvectormap-1.2.2.css" rel="stylesheet">
    <!-- Custom styles -->
    <link rel="stylesheet" href="~/css/fullcalendar.css">
    <link href="~/css/widgets.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/style-responsive.css" rel="stylesheet" />
    @*<link href="~/css/xcharts.min.css" rel="stylesheet">*@
    <link href="~/css/jquery-ui-1.10.4.min.css" rel="stylesheet">
    <link href="~/Content/toastr.css" rel="stylesheet" />

    <link href="~/Content/Common.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
    <!--[if lt IE 9]>
      <script src="~/js/html5shiv.js"></script>
      <script src="~/js/lte-ie7.js"></script>
    <![endif]-->
</head>
<body>
    @*<div id="note">
            Hệ thống sẽ gởi thông báo khi có việc được giao. Bạn hãy <a href="javascript:void(0)" id="subscribe">Cho phép nhận thông báo </a> trên trình duyệt.<br />. <a id="close">[close]</a>
        </div>*@
    <section id="container" class="">
        @Html.Action("HeadMasterPartial", "Shared")

        <!--sidebar start-->
        @Html.Action("MenuLeftMasterPartial", "Shared")
        <!--sidebar end-->
        <!--main content start-->

        <section id="main-content">
            <section class="wrapper">

                @RenderBody()
            </section>
        </section>
        <!--main content end-->
    </section>
    @*<script src="~/Scripts/Boostrap/bootstrap.js"></script>*@
    <script src="~/Scripts/jquery-ui-1.11.4.js"></script>
    @*Knock Out*@
    <script src="~/Scripts/knockout-2.1.0.js"></script>
    <script src="~/Scripts/knockout-2.1.0.debug.js"></script>
    <script src="~/Scripts/jtable.2.4.0/jquery.jtable.js"></script>
    <script src="~/Scripts/jtable.2.4.0/localization/jquery.jtable.vi.js"></script>
    <script src="~/Scripts/jquery.alerts.js"></script>
    <script src="~/Scripts/VINASIC/date.format.js"></script>
    <script src="~/Scripts/VINASIC/common.js"></script>
    <!-- nice scroll -->
    <script src="~/js/jquery.scrollTo.min.js"></script>
    <script src="~/js/jquery.nicescroll.js" type="text/javascript"></script>
    @*<script src="~/Scripts/jquery.nicescroll.js"></script>*@
    <!-- charts scripts -->
    <script src="~/assets/jquery-knob/js/jquery.knob.js"></script>
    <script src="~/js/jquery.sparkline.js" type="text/javascript"></script>
    @*<script src="~/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>*@
    <script src="~/js/owl.carousel.js"></script>
    <!-- jQuery full calendar -->
    <
    <script src="~/js/fullcalendar.min.js"></script>
    <!-- Full Google Calendar - Calendar -->
    <script src="~/assets/fullcalendar/fullcalendar/fullcalendar.js"></script>
    <script src="~/fullcalendar/libCalendar/moment.min.js"></script>
    <!--script for this page only-->
    <script src="~/js/calendar-custom.js"></script>
    <script src="~/js/jquery.rateit.min.js"></script>
    <!-- custom select -->
    <script src="~/js/jquery.customSelect.min.js"></script>
    @*<script src="~/assets/chart-master/Chart.js"></script>*@
    <!--custome script for all page-->
    <script src="~/js/scripts.js?ver=1.8"></script>
    <!-- custom script for this page-->
    @*<script src="~/assets/chart-master/Chart.js"></script>
        <script src="~/js/chartjs-custom.js"></script>
        <script src="~/js/sparkline-chart.js"></script>
        <script src="~/js/easy-pie-chart.js"></script>
        <script src="~/js/jquery-jvectormap-1.2.2.min.js"></script>
        <script src="~/js/jquery-jvectormap-world-mill-en.js"></script>
        <script src="~/js/xcharts.min.js"></script>*@
    <script src="~/js/jquery.autosize.min.js"></script>
    <script src="~/js/jquery.placeholder.min.js"></script>
    <script src="~/js/gdp-data.js"></script>
    <script src="~/js/morris.min.js"></script>
    <script src="~/js/sparklines.js"></script>
    <script src="~/js/charts.js"></script>
    <script src="~/js/jquery.slimscroll.min.js"></script>
    <!-- Include SignalR -->
    <script src="/Scripts/jquery.signalR-2.2.0.js"></script>
    <script src="@Url.Content("~/signalr/hubs")" type="text/javascript"></script>
    <script src="~/Scripts/toastr.js"></script>
    <script src="~/service-worker1.1.js"></script>
    <script src="~/Scripts/VINASIC/push-notification.js"></script>
</body>
</html>